[general]
live_config_reload = true

[terminal]
shell = {program = "powershell.exe", args = ["-NoLogo"]}
osc52 = "CopyPaste"

[font]
normal = {family = "HackGen Console NF", style="Regular"}
size = 16

[keyboard]
bindings = [
    { key="Space", mods="Control", chars="\u0000" },
    { key="Enter", mods="Alt", action="SpawnNewInstance"}
    ]